spring:
  jta:
    enabled: true

    atomikos:
      datasource:
        message:
          unique-resource-name: messageDataSource
          xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
          xa-properties:
            user: sa
            password:
            url: jdbc:h2:mem:message;DB_CLOSE_DELAY=-1

        audit:
          unique-resource-name: auditDataSource
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            user: root
            password:
            url: jdbc:mysql://localhost:3306/audit?createDatabaseIfNotExist=true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
